### ISSUE TITLE
Please upgrade momentjs

### ISSUE THREAD

**Issue by paulrutter** [nanlabs/econsole#7]
Following https://nodesecurity.io/advisories/55, momentjs 2.6.0 has a security vulnerability.
Please upgrade to at least 2.11.2 in order to fix this.

**Comment by jalessandro** [comment]
Hey @paulrutter! I made the upgrade. Thanks for the notice!

**Comment by paulrutter** [comment]
Np, thanks for the quick fix!

**Comment by paulrutter** [comment]
Np, thanks for the quick fix!

**Comment by paulrutter** [comment]
There is a security advisory again, see https://github.com/nanlabs/econsole/pull/9.
